### ISSUE TITLE
About the generation setting of the paper

### ISSUE THREAD

**Issue by Heisenburger2020** [qiuk2/AAR#5]
Hi, authors. It is an interesting work. But I am confused about the setting of the work. Previous audio generation models, like AudioGen, usually follow the evaluation protocols to generate 10s audio as a whole. This is also the general setting of AudioSet. But I find in AAR,  1s audio are generated by auto-regressive modeling instead of 10s. I am just curious about why AAR does not follow the general settings. Will the performance of AAR generation degrade a lot if generating a 10s audio? Or Does the training/inference cost become the bottleneck?

**Comment by qiuk2** [comment]
Thanks for your intereset for our AAR. Directly generating 10s audio may lead to a superior performance while our available computes do not support us to train that AR model. We will work on releasing 10s models in the near future. 

Though our setting is slightly different from the setting in AudioGen, ablation experiments in our paper can also demonstrate the advantage of our proposed method. If you have further question, please feel free to ask.
